<a href="https://colab.research.google.com/github/getitjessica/testHU/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy (short for Numerical Python) provides an efficient interface to store and operate on dense data buffers. In some ways, NumPy arrays are like Python's built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size. NumPy arrays form the core of nearly the entire ecosystem of data science tools in Python, so time spent learning to use NumPy effectively will be valuable no matter what aspect of data science interests you.

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

a.shape

(2, 3)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a[0]

#a[2]

1

In [ ]:
a[0] = 10

a

array([10,  2,  3,  4,  5,  6])

In [ ]:
a[:3]

array([10,  2,  3])

In [ ]:
b = a[3:]

b

array([40,  5,  6])

In [ ]:
b[0] = 45


b

array([45,  5,  6])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[1, 3]

8

In [ ]:
a.ndim

2

In [ ]:
a.shape

(3, 4)

In [ ]:
a.size

12

In [ ]:
a.dtype

dtype('int64')

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
# Create an empty array with 2 elements
np.empty(2)

array([0., 0.])

In [ ]:
np.arange(4)


array([0, 1, 2, 3])

In [ ]:
# first number, last number, and the step size.
np.arange(2, 9, 2)


array([2, 4, 6, 8])